### ISSUE TITLE
Feature Request: support per-zone allow-transfter statements w/ keys in BIND

### ISSUE THREAD

**Issue by gclawes** [bodsch/ansible-collection-dns#14]
##### SUMMARY
Support for per-zone `allow-transfer` statements in bind (configurable in `bind_zones:`) would be useful for doing per-zone permissioning of keys to zones.

This would useful for tools like [`external-dns` RFC2136 provider](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md), where where zone transfers are used to read the current state of a domain for incremental updates.  With this tool, if TSIG is used for updates, it must also be used for zone transfers.

There is not currently a good way to configure `allow-transfer { key "my-key-name" };` statements (either per-zone or globally).  `bind_acls` (which renders global `allow-transfer` blocks) cannot be used for this because there is no way to set the `key` statement.

##### ADDITIONAL INFORMATION
Role configuration could look something like this:
```
bind_zones
  - name: "test.example.com"
    type: primary
    name_servers:
      - "ns01.example.com"
    hostmaster_email: admin
    allow_update:
      - 'key "external-dns"'
    allow_transfers:
      - 'key "external-dns"'

bind_dns_keys:
  - name: external-dns
    algorithm: hmac-sha256
    secret: "azertyAZERTY123456"
```

To result in this config:
`/etc/bind/auth-transfer.conf`
```
server 192.0.2.3 {
  keys {  external-dns;  };
};

key external-dns {
  algorithm hmac-sha256;
  secret "azertyAZERTY123456"
};
```

`/etc/bind/named.conf`
```
...
include "/etc/bind/auth-transfer.conf";
...
zone "test.example.com" IN {
  type master;
  file "/var/cache/bind/test.example.com";
  notify yes;
  allow-update {
    key "external-dns";
  };
  allow-transfer {
    key "external-dns";
  };
};
```
